name: 'EKS Terraform workflow'

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      - name: Terraform Init
        run: |
          cd EKS 
          terraform init -backend-config="bucket=${{ secrets.TERRAFORM_BUCKET }}" -backend-config="dynamodb_table=terraform-cicd-lock"

      - name: Terraform Validate
        run: |
          cd EKS 
          terraform validate

      - name: Terraform Apply
        id: terraform-apply
        run: |
          cd EKS 
          terraform apply -auto-approve
        env:
          TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
          TF_VAR_iam_role_arn: ${{ secrets.IAM_ROLE_ARN }}
